projectName: mobile
squashClients: false
clientPostfix: Client

apis:
  api:
    rootClient: true
    schemaPath: ../api/openapi.json
    classPostfix: Service
    putClientsIn: lib/core/network/api/
    putModelsIn: lib/core/models/
